/** HR Studio Guide — all 40 enterprise features documented for UK FinTech. */

export type HrGuideFeature = {
  id: number;
  name: string;
  purpose: string;
  where: string;
  steps: string;
  benefit: string;
  group: string;
};

export const HR_GUIDE_FEATURES: HrGuideFeature[] = [
  {
    id: 1,
    name: 'Visual Kanban Hiring Board',
    purpose: 'Drag or move applicants across Applied → Hired/Rejected. Public /careers applications land in Applied automatically.',
    where: 'HR → ATS Recruitment',
    steps: 'Open a card → change stage via column actions or drag handle. Refresh after a careers apply to see the new candidate.',
    benefit: 'Transparent pipeline visibility for regulated hiring decisions.',
    group: 'ATS & Recruitment',
  },
  {
    id: 2,
    name: 'AI Resume Score & Matcher',
    purpose: 'Extracts text from the uploaded resume (PDF/DOCX) and scores 0–100% against the job description and AI Match Keywords from the Enterprise Job Editor.',
    where: 'ATS Applications / Kanban / candidate profile — score badge next to Resume',
    steps: 'In Enterprise Job Editor, add comma-separated AI Match Keywords → publish. New /careers applicants are scored on insert.',
    benefit: 'Faster shortlists without bias toward formatting alone.',
    group: 'ATS & Recruitment',
  },
  {
    id: 3,
    name: 'UK Background & DBS Check Tracker',
    purpose: 'Tracks financial/criminal verification status.',
    where: 'Applicant card → Background badge',
    steps: 'Cycle status: not started → DBS pending → clear/flagged.',
    benefit: 'Supports FCA fitness & propriety expectations.',
    group: 'ATS & Recruitment',
  },
  {
    id: 4,
    name: 'One-Click Interview Scheduler',
    purpose: 'Schedule calls and capture interview notes.',
    where: 'ATS → Schedule Interview modal',
    steps: 'Pick datetime → save notes → stage moves to Interview.',
    benefit: 'Audit-ready interview trail.',
    group: 'ATS & Recruitment',
  },
  {
    id: 5,
    name: 'Automated Email Templates',
    purpose: 'Interview invite or polite rejection copy.',
    where: 'ATS → Email actions on card',
    steps: 'Click Invite or Reject email → copy/send via mailto.',
    benefit: 'Consistent, professional candidate communications.',
    group: 'ATS & Recruitment',
  },
  {
    id: 6,
    name: 'Offer Letter Generator',
    purpose: 'Digital offer with £ GBP salary & PAYE snapshot.',
    where: 'ATS → Generate Offer',
    steps: 'Enter salary GBP → generate HTML letter → move to Offer stage.',
    benefit: 'Clear compensation transparency in UK terms.',
    group: 'ATS & Recruitment',
  },
  {
    id: 7,
    name: 'Candidate Scorecards',
    purpose: 'Structured tech + culture evaluation.',
    where: 'ATS → Scorecard panel',
    steps: 'Rate technical/culture fit 1–5 and save notes.',
    benefit: 'Defensible hiring decisions.',
    group: 'ATS & Recruitment',
  },
  {
    id: 8,
    name: 'Duplicate Applicant Flag',
    purpose: 'Alerts if email applied before.',
    where: 'ATS card — Duplicate badge',
    steps: 'System flags on create when email already exists.',
    benefit: 'Prevents double-processing and policy gaming.',
    group: 'ATS & Recruitment',
  },
  {
    id: 9,
    name: 'Talent Pool Archive',
    purpose: 'Save strong second-choice candidates.',
    where: 'ATS → Add to Talent Pool',
    steps: 'Toggle talent pool; filter Talent Pool tab.',
    benefit: 'Reuse warm talent for future requisitions.',
    group: 'ATS & Recruitment',
  },
  {
    id: 10,
    name: 'Source of Hire Analytics',
    purpose: 'Chart LinkedIn / Direct / Referral sources.',
    where: 'ATS → Analytics strip',
    steps: 'Set source on applicants; review distribution chart.',
    benefit: 'Optimise recruiting spend.',
    group: 'ATS & Recruitment',
  },
  {
    id: 11,
    name: 'FCA Compliance Onboarding Checklist',
    purpose: 'Track mandatory UK compliance training.',
    where: 'Employees → Compliance column',
    steps: 'Mark FCA trained when modules complete.',
    benefit: 'Demonstrates staff competence for regulated activities.',
    group: 'Onboarding & Attendance',
  },
  {
    id: 12,
    name: 'Smart Remote Attendance Log',
    purpose: 'Check-in/out with IP/location tags.',
    where: 'HR → Attendance',
    steps: 'Log check-in; later check-out with optional location.',
    benefit: 'Evidence for remote-working policies.',
    group: 'Onboarding & Attendance',
  },
  {
    id: 13,
    name: 'Leave Management Engine',
    purpose: 'Sick/Casual/Annual leave with 1-click approve.',
    where: 'Employees & Leaves / Quick Create',
    steps: 'Submit leave → HR Approves or Rejects.',
    benefit: 'Fair, auditable time-off governance.',
    group: 'Onboarding & Attendance',
  },
  {
    id: 14,
    name: 'UK Public Holiday Calendar',
    purpose: 'Highlight England & Wales bank holidays.',
    where: 'Attendance → UK Holidays toggle',
    steps: 'Toggle calendar to plan coverage.',
    benefit: 'Avoid scheduling conflicts on bank holidays.',
    group: 'Onboarding & Attendance',
  },
  {
    id: 15,
    name: 'NDA & Policy Acknowledgement Vault',
    purpose: 'Track signed confidentiality agreements.',
    where: 'Employees → NDA badge',
    steps: 'Mark NDA signed after DocuSign/vault upload.',
    benefit: 'Protects lender IP and customer data.',
    group: 'Onboarding & Attendance',
  },
  {
    id: 16,
    name: 'Probation Monitoring',
    purpose: 'Flags 30/60/90 day reviews.',
    where: 'Employees → Probation alerts',
    steps: 'Set probation dates; review flagged staff weekly.',
    benefit: 'Structured performance during probation.',
    group: 'Onboarding & Attendance',
  },
  {
    id: 17,
    name: 'Overtime Tracker',
    purpose: 'Extra hours with manager sign-off.',
    where: 'Attendance → Overtime',
    steps: 'Log hours → manager signs off for payroll.',
    benefit: 'Accurate GBP payroll adjustments.',
    group: 'Onboarding & Attendance',
  },
  {
    id: 18,
    name: 'Burnout Risk Indicator',
    purpose: 'Flags no leave 90+ days or chronic OT.',
    where: 'Employees → Burnout badge',
    steps: 'Review flagged people; encourage leave.',
    benefit: 'Duty of care and retention.',
    group: 'Onboarding & Attendance',
  },
  {
    id: 19,
    name: 'Asset Allocation Tracker',
    purpose: 'Laptops, keys, test devices.',
    where: 'Employees → Assets',
    steps: 'Allocate asset → collect on offboarding.',
    benefit: 'Security & inventory control.',
    group: 'Onboarding & Attendance',
  },
  {
    id: 20,
    name: 'Role Access Provisioning Request',
    purpose: 'Ticket tech to grant/revoke admin access.',
    where: 'Employees → Access request',
    steps: 'Submit grant/revoke → Admin Access team completes.',
    benefit: 'Least-privilege access discipline.',
    group: 'Onboarding & Attendance',
  },
  {
    id: 21,
    name: 'UK Salary & Payslip Vault',
    purpose: 'Basic, HRA, pension, NI in £ GBP.',
    where: 'Payroll £',
    steps: 'Open employee → review breakdown.',
    benefit: 'Transparent UK compensation records.',
    group: 'Payroll & Performance',
  },
  {
    id: 22,
    name: 'Estimated PAYE Viewer',
    purpose: 'Preview UK tax bands & NI.',
    where: 'Payroll → PAYE estimate',
    steps: 'Select employee gross → view tax/NI/net.',
    benefit: 'Helps explain take-home to staff.',
    group: 'Payroll & Performance',
  },
  {
    id: 23,
    name: 'Expense Reimbursement Portal',
    purpose: 'Travel/software claims with receipts.',
    where: 'Payroll / Quick Create → Expense',
    steps: 'Submit claim → HR approve (exec if >£500).',
    benefit: 'Controlled spend with audit trail.',
    group: 'Payroll & Performance',
  },
  {
    id: 24,
    name: 'Quarterly KPI & OKR Tracker',
    purpose: 'Goals with progress bars.',
    where: 'Performance',
    steps: 'Add quarterly goal → update % progress.',
    benefit: 'Aligns teams to lender OKRs.',
    group: 'Payroll & Performance',
  },
  {
    id: 25,
    name: '360° Peer Feedback',
    purpose: 'Manager/peer appraisal notes.',
    where: 'Performance → Feedback',
    steps: 'Log rating + constructive note.',
    benefit: 'Richer performance evidence.',
    group: 'Payroll & Performance',
  },
  {
    id: 26,
    name: 'Incentive & Bonus Calculator',
    purpose: '£ bonus from KPI achievement.',
    where: 'Performance → Bonus',
    steps: 'KPI score drives suggested bonus GBP.',
    benefit: 'Fair, formula-based incentives.',
    group: 'Payroll & Performance',
  },
  {
    id: 27,
    name: 'Contractor vs FTE Tagging',
    purpose: 'Classify for tax/regulatory treatment.',
    where: 'Employees → Employment type',
    steps: 'Tag full_time or contractor on profile.',
    benefit: 'IR35 / employment status clarity.',
    group: 'Payroll & Performance',
  },
  {
    id: 28,
    name: 'Anonymous Grievance Box',
    purpose: 'Secure whistleblower reporting.',
    where: 'Performance → Grievance',
    steps: 'Submit anonymous subject/body.',
    benefit: 'SMCR / speak-up culture compliance.',
    group: 'Payroll & Performance',
  },
  {
    id: 29,
    name: 'Offboarding & Exit Interview',
    purpose: 'Revoke access, collect assets, notes.',
    where: 'Employees → Offboard',
    steps: 'Start checklist → complete exit interview.',
    benefit: 'Secure leaver process.',
    group: 'Payroll & Performance',
  },
  {
    id: 30,
    name: 'Audit Trail Export',
    purpose: 'Export HR actions to CSV.',
    where: 'Payroll / Guide → Export Audit',
    steps: 'Click Export CSV for regulators.',
    benefit: 'Ready evidence for audits.',
    group: 'Payroll & Performance',
  },
  {
    id: 31,
    name: 'Monthly Headcount Budget Burn',
    purpose: 'Total monthly payroll £ spend.',
    where: 'Admin → HR Overview',
    steps: 'Open widget for burn rate.',
    benefit: 'Executive cost control.',
    group: 'Executive Intelligence',
  },
  {
    id: 32,
    name: 'Attrition & Retention Risk',
    purpose: 'AI-style department turnover risk.',
    where: 'Admin HR Overview',
    steps: 'Review risk score; engage managers.',
    benefit: 'Protect critical FinTech talent.',
    group: 'Executive Intelligence',
  },
  {
    id: 33,
    name: 'Budget Approval Workflow',
    purpose: 'Admin approves headcount budget.',
    where: 'Admin HR Overview → Headcount',
    steps: 'HR requests → Admin Approves.',
    benefit: 'Prevents unbudgeted hiring.',
    group: 'Executive Intelligence',
  },
  {
    id: 34,
    name: 'Executive Headcount Breakdown',
    purpose: 'Employees, contractors, vacancies.',
    where: 'Admin HR Overview counters',
    steps: 'Glance live counters.',
    benefit: 'Instant workforce composition.',
    group: 'Executive Intelligence',
  },
  {
    id: 35,
    name: 'Department Cost Center Chart',
    purpose: 'Tech vs Marketing vs Ops salary spend.',
    where: 'Admin HR Overview chart',
    steps: 'Compare department GBP spend.',
    benefit: 'Allocate budget to growth areas.',
    group: 'Executive Intelligence',
  },
  {
    id: 36,
    name: 'High-Performer Leaderboard',
    purpose: 'Top KPI achievers for execs.',
    where: 'Admin HR Overview',
    steps: 'Celebrate / retain top talent.',
    benefit: 'Culture of excellence.',
    group: 'Executive Intelligence',
  },
  {
    id: 37,
    name: 'Pending Critical Actions',
    purpose: 'Expense >£500 or salary increments awaiting sign-off.',
    where: 'Admin HR Overview alerts',
    steps: 'Clear critical queue weekly.',
    benefit: 'No stalled high-value approvals.',
    group: 'Executive Intelligence',
  },
  {
    id: 38,
    name: 'Internal Referral Bonus Tracker',
    purpose: '£ referral payouts when hires succeed.',
    where: 'Admin / ATS referrals',
    steps: 'Track pending → mark paid.',
    benefit: 'Incentivises quality referrals.',
    group: 'Executive Intelligence',
  },
  {
    id: 39,
    name: 'Anniversary & Birthday Widget',
    purpose: 'Upcoming culture milestones.',
    where: 'Admin HR Overview',
    steps: 'Send recognition notes.',
    benefit: 'Builds belonging.',
    group: 'Executive Intelligence',
  },
  {
    id: 40,
    name: 'Zero-Flicker Skeleton Loading',
    purpose: 'animate-pulse skeletons while fetching.',
    where: 'All HR tabs',
    steps: 'Automatic during loads.',
    benefit: 'Premium, trustworthy UX.',
    group: 'Executive Intelligence',
  },
  {
    id: 41,
    name: 'Public Careers Sync (/careers)',
    purpose:
      'Open ATS job postings with publish enabled automatically appear on the public /careers page as glassmorphic role cards (£ GBP salary bands).',
    where: 'HR Settings → Public careers sync · ATS → Enterprise Job Editor → Publish checkbox',
    steps:
      'Create a job in the Enterprise Editor, set £ min–max, tick “Publish to ATS as Open & sync to /careers”, ensure HR Settings sync toggle is on. Visit /careers to confirm the listing.',
    benefit: 'Single source of truth — no duplicate marketing copy for open roles.',
    group: 'ATS & Recruitment',
  },
  {
    id: 42,
    name: 'Enterprise Job Editor',
    purpose:
      'Spacious 2-column creator for title, department, employment type, working model (Remote / On-site / Hybrid), £ GBP salary band, description, FCA responsibilities, and AI Match Keywords.',
    where: 'ATS Recruitment → + Create job (or Quick Create → Post New Job)',
    steps:
      'Fill metadata on the left, rich details on the right, add comma-separated AI keywords, then create. Use polished validation messages if fields are missing.',
    benefit: 'Detail-rich requisitions improve matcher quality and candidate clarity.',
    group: 'ATS & Recruitment',
  },
  {
    id: 43,
    name: 'Careers → ATS Application Pipeline',
    purpose:
      'Candidates open a job detail drawer on /careers, apply with name, email, LinkedIn, and PDF resume; the record is inserted into job_applicants at Applied with an AI match score.',
    where: 'Public /careers → View role → Apply Now · HR → ATS Kanban (Applied column)',
    steps:
      'After a public apply, open ATS Recruitment — the candidate appears in Applied linked to the job, ready for shortlist / interview.',
    benefit: 'Zero manual re-entry from careers inbox into the hiring board.',
    group: 'ATS & Recruitment',
  },
];
